### ISSUE TITLE
Documentation is inconsistent

### ISSUE THREAD

**Issue by jimmcnulty41** [Adobe-CEP/Samples#76]
The documentation for using Adobe-CEP is inconsistent and makes it more difficult for developers to get up and running on an Adobe-CEP project. 

Various links on Adobe.io pages, and all cookbooks included in the Adobe-CEP Resources Repo link to extension builder 3.

**Comment by undavide** [comment]
That's the reason why I've (very sort-of) thrived producing exclusive training content ;-)

**Comment by videohead** [comment]
Bruce B had a great brief on how to build a Premiere Panel. Maybe that could be updated as a starter?
I know we are all busy, but it does not speak well of the dev community (or of Adobe) when we can't build and maintain capable docs to support the project that we are using. I am happy to help where I can.

**Comment by bbb999** [comment]
Aww, thanks Matthew! ;)

That write-up still exists, and is current for PPro 12.0; most of it is applicable to other hosts.

https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/ReadMe.md

**Comment by jimmcnulty41** [comment]
@ErinFinnegan Looks like I got confused about sub-domains. The links to extension builder 3 were on adobe.com. Reviewing my search history, I think the main confusion arose because Extension Builder 3 seemed like a lower-effort entry point into getting a "Hello World" to work.  However, the ZXPSignCmd.exe + ExManCmd seems to be the way to go.

I was coming to CEP via After Effects, so I did not see @bbb999 's Sample, but I think it would make a great entry point to clear away a lot of the confusion around exactly what kind of boilerplate is required to get up and running. Having a version of that near the top of the cookbooks would be very helpful for people trying to get started.

It may even be useful to have a separate CEP-Templates repository that contains only the bare minimum boilerplate.

If there's any way I can help, let me know


### For reference:
The adobe.com links that had led me astray:
(I think that improved documentation in these repos would have prevented me from getting confused by the following for reasons noted after the links, but since I was finding little luck otherwise, I decided to give them a try)
http://www.adobe.com/devnet/creativesuite/articles/a-short-guide-to-HTML5-extensions.html - says optional
http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/creativesuite/pdfs/SigningTechNote_CC.pdf - notes as one of 3 options
https://www.adobe.com/devnet/creativesuite/articles/multiple-extensions.html - this one is from 2011

**Comment by ErinFinnegan** [comment]
@jimmcnulty41 

I think you might be pleased to find that we're doing a series of blog posts on the I/O blog about getting started.  [This Wednesday's post](https://medium.com/adobe-io/how-to-create-your-first-adobe-panel-in-6-easy-steps-f8bd4ed5778) would've really helped you out!

The Extension Builder, or ExtendScript Toolkit are technically optional.

Making it easier to get started and building some simple boilerplates are a few of my teams' goals for this year.

**Comment by b-rad-c** [comment]
I would like to add to this discussion that what I think is lacking is a full api documentation page. I have found many tutorials and walkthroughs but most times that I learn a new library or api there are these walkthrough guides in addition to documentation for every function and object, and that's what I cannot find online.

For example, I'm writing a plugin for premiere pro right now and I am able to get and set an in/out point on a clip, the only reason I can do that is because I can see the method exists on the object in extend script toolkit and trial by error allows me to use it. I can also see the clearInPoint and clearOutPoint methods in extend script, but they are not working as expected and I cannot find an example in the repositories. If there were a page explaining the functions' purpose, arguments, expected return value(s) and potentially exceptions raised I could tell if I am doing it wrong or expecting the wrong outcome but right now I am flying blind.

Bruce is very pleasant and knowledgeable and has always helped find me the right answers but with a full api documentation I could bother him less and move quicker in my development.

**Comment by bbb999** [comment]
PPro API documentation, in progress:

http://ppro.aenhancers.com

Yes, more docs/tutorials could improve the panel development on boarding experience. There are also hundreds of PPro panels used world-wide every day, so we feel confident devs can be successful.

**Comment by ErinFinnegan** [comment]
> I would like to add to this discussion that what I think is lacking is a full api documentation page. I have found many tutorials and walkthroughs but most times that I learn a new library or api there are these walkthrough guides in addition to documentation for every function and object, and that's what I cannot find online.

@b-rad-c We've been working on some new walk-through guides and sample extensions and started adding them to this repository: https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Network%20requests%20and%20responses%20with%20Fetch

**Comment by ashryanbeats** [comment]
Hi all,

Closing this issue in favor of having issues for specific asks regarding the documentation. This was fair feedback, but very broad in scope.

Since this issue was opened in January, several big things have happened here which should improve your onboarding and development experience:

1. We now have [Getting Started guides in a new repo](https://github.com/Adobe-CEP/Getting-Started-guides)
2. Those Getting Started guides include, as of this week, a Package/Distribute/Install guide
3. This Samples repo has been completely refreshed and updated
4. Both repos now have contribution guidelines, and issue- and PR-templates
5. More of us are keeping an eye on these inbound channels now

If you want to do a little background reading on some of the above, here are a couple of blog posts to check out:

1. [New CEP Getting Started resources on GitHub](https://medium.com/adobetech/new-cep-getting-started-resources-on-github-2cf5252523)
2. [How to Package, Distribute, and Install Your Creative Cloud Extension](https://medium.com/adobetech/how-to-package-distribute-and-install-your-creative-cloud-extension-8eec6da31009)

We know these efforts won't cover everything you might want to see, and we do have some more in store for CEP documentation later in the year.

In the interim, please feel free to open issues or submit PRs on specific feedback or asks.

Thanks for building on Creative Cloud products with CEP!
