### ISSUE TITLE
Example for building a Photoshop panel with Angular 7 and Typescript

### ISSUE THREAD

**Issue by NaviMarella** [Adobe-CEP/Samples#96]
# Submit an issue

## Topic

This is an issue regarding:

- Sample to showcase building CEP Panels with UI frameworks.

## Description of the issue

The samples contained within this repo doesn't show how to build UI with any of the existing UI frameworks like React, Angular. I would like to have an example to show how to build a CEP Panel with Angular so we can integrate this with Typescript.

I would like to send a PR for this.

**Comment by dkstevekwak** [comment]
@NaviMarella absolutely! if you have a completed PR for this, please feel free to go ahead and submit it for review.

**Comment by NaviMarella** [comment]
@dkstevekwak 

Sure, I will send a PR within a couple of days.

I feel this helps a lot of front-end developers, to use their skills in building more CEP panels reused across the community.

**Comment by dkstevekwak** [comment]
Closing this issue as it's a suggest PR now

**Comment by SturmB** [comment]
Has this gotten anywhere? I, too, would very much like to see some examples on how to integrate Angular with Adobe CEP.

**Comment by NaviMarella** [comment]
Actually it's been a long time i haven't working on this.

Here is the sample MR sent for one of the other repos, this covers how to integrate Angular with CEP.

https://github.com/undavide/PS-Panels-Boilerplate/pull/2

**Comment by ErinFinnegan** [comment]
Hi @SturmB, I've been meaning to reply here...

Davide's example is probably the way to go! However, a year or so from now, once UXP is in Photoshop, the way that you might deploy Angular will be very different; hopefully simpler, and at best you may find you don't need to use Angular, depending on your use case.

**Comment by SturmB** [comment]
Thanks, @NaviMarella, I'll have a look at that and see if I can figure it out.

@ErinFinnegan, I'm afraid this is the first I'm hearing about UXP. I just spent a few minutes looking it up and it appears to be something that's always just over the horizon. Don't get me wrong, I'd love for a more modern and easier approach to creating extensions, which is why I was looking for a way to integrate TypeScript and Angular (or React) into CEP development. I also hope UXP will be available for all of the CC apps, not just Photoshop. But since, as you say, it is at least a year from release, I might as well move our old, massive, spaghetti-code ExtendScript scripts to CEP and utilize OOP principles and TypeScript safety now. Adding in a framework like Angular or React would just make it even better.
